/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_msvcr71(void);

const struct test winetest_testlist[] =
{
    { "msvcr71", func_msvcr71 },
    { 0, 0 }
};
