/*** Autogenerated by WIDL 8.6 from dlls/comsvcs/comsvcs_classes.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __comsvcs_classes_h__
#define __comsvcs_classes_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __NewMoniker_FWD_DEFINED__
#define __NewMoniker_FWD_DEFINED__
#ifdef __cplusplus
typedef class NewMoniker NewMoniker;
#else
typedef struct NewMoniker NewMoniker;
#endif /* defined __cplusplus */
#endif /* defined __NewMoniker_FWD_DEFINED__ */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * NewMoniker coclass
 */

DEFINE_GUID(CLSID_NewMoniker, 0xecabafc6, 0x7f19, 0x11d2, 0x97,0x8e, 0x00,0x00,0xf8,0x75,0x7e,0x2a);

#ifdef __cplusplus
class DECLSPEC_UUID("ecabafc6-7f19-11d2-978e-0000f8757e2a") NewMoniker;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(NewMoniker, 0xecabafc6, 0x7f19, 0x11d2, 0x97,0x8e, 0x00,0x00,0xf8,0x75,0x7e,0x2a)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __comsvcs_classes_h__ */
