/*** Autogenerated by WIDL 8.6 from programs/rpcss/irpcss.idl - Do not edit ***/
#include <string.h>

#include "irpcss.h"

#ifndef DECLSPEC_HIDDEN
#define DECLSPEC_HIDDEN
#endif

#ifndef USE_COMPILER_EXCEPTIONS

#include "wine/exception.h"
#undef RpcTryExcept
#undef RpcExcept
#undef RpcEndExcept
#undef RpcTryFinally
#undef RpcFinally
#undef RpcEndFinally
#undef RpcExceptionCode
#undef RpcAbnormalTermination

struct __exception_frame;
typedef int (*__filter_func)(struct __exception_frame *);
typedef void (*__finally_func)(struct __exception_frame *);

#define __DECL_EXCEPTION_FRAME \
    EXCEPTION_REGISTRATION_RECORD frame; \
    __filter_func                 filter; \
    __finally_func                finally; \
    __wine_jmp_buf                jmp; \
    DWORD                         code; \
    unsigned char                 abnormal_termination; \
    unsigned char                 filter_level; \
    unsigned char                 finally_level;

struct __exception_frame
{
    __DECL_EXCEPTION_FRAME
};

static inline void __widl_unwind_target(void)
{
    struct __exception_frame *exc_frame = (struct __exception_frame *)__wine_get_frame();
    if (exc_frame->finally_level > exc_frame->filter_level)
    {
        exc_frame->abnormal_termination = 1;
        exc_frame->finally( exc_frame );
        __wine_pop_frame( &exc_frame->frame );
    }
    exc_frame->filter_level = 0;
    __wine_longjmp( &exc_frame->jmp, 1 );
}

static DWORD __cdecl __widl_exception_handler( EXCEPTION_RECORD *record,
                                               EXCEPTION_REGISTRATION_RECORD *frame,
                                               CONTEXT *context,
                                               EXCEPTION_REGISTRATION_RECORD **pdispatcher )
{
    struct __exception_frame *exc_frame = (struct __exception_frame *)frame;

    if (record->ExceptionFlags & (EH_UNWINDING | EH_EXIT_UNWIND | EH_NESTED_CALL))
    {
        if (exc_frame->finally_level && (record->ExceptionFlags & (EH_UNWINDING | EH_EXIT_UNWIND)))
        {
            exc_frame->abnormal_termination = 1;
            exc_frame->finally( exc_frame );
        }
        return ExceptionContinueSearch;
    }
    exc_frame->code = record->ExceptionCode;
    if (exc_frame->filter_level && exc_frame->filter( exc_frame ) == EXCEPTION_EXECUTE_HANDLER)
        __wine_rtl_unwind( frame, record, __widl_unwind_target );
    return ExceptionContinueSearch;
}

#define RpcTryExcept \
    if (!__wine_setjmpex( &__frame->jmp, &__frame->frame )) \
    { \
        if (!__frame->finally_level) \
            __wine_push_frame( &__frame->frame ); \
        __frame->filter_level = __frame->finally_level + 1;

#define RpcExcept(expr) \
        if (!__frame->finally_level) \
            __wine_pop_frame( &__frame->frame ); \
        __frame->filter_level = 0; \
    } \
    else \

#define RpcEndExcept

#define RpcExceptionCode() (__frame->code)

#define RpcTryFinally \
    if (!__frame->filter_level) \
        __wine_push_frame( &__frame->frame ); \
    __frame->finally_level = __frame->filter_level + 1;

#define RpcFinally \
    if (!__frame->filter_level) \
        __wine_pop_frame( &__frame->frame ); \
    __frame->finally_level = 0;

#define RpcEndFinally

#define RpcAbnormalTermination() (__frame->abnormal_termination)

#define RpcExceptionInit(filter_func,finally_func) \
    do { \
        __frame->frame.Handler = __widl_exception_handler; \
        __frame->filter = (__filter_func)(filter_func); \
        __frame->finally = (__finally_func)(finally_func); \
        __frame->abnormal_termination = 0; \
        __frame->filter_level = 0; \
        __frame->finally_level = 0; \
    } while (0)

#else /* USE_COMPILER_EXCEPTIONS */

#define RpcExceptionInit(filter_func,finally_func) \
    do { (void)(filter_func); } while(0)

#define __DECL_EXCEPTION_FRAME \
    DWORD code;

#endif /* USE_COMPILER_EXCEPTIONS */

struct __server_frame
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
};

static int __server_filter( struct __server_frame *__frame )
{
    return (__frame->code == STATUS_ACCESS_VIOLATION) ||
           (__frame->code == STATUS_DATATYPE_MISALIGNMENT) ||
           (__frame->code == RPC_X_BAD_STUB_DATA) ||
           (__frame->code == RPC_S_INVALID_BOUND);
}

#define TYPE_FORMAT_STRING_SIZE 67
#define PROC_FORMAT_STRING_SIZE 45

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * ObjectRpcBaseTypes interface
 */

/*****************************************************************************
 * Irpcss interface
 */

static RPC_DISPATCH_TABLE Irpcss_v0_0_DispatchTable;
static const MIDL_SERVER_INFO Irpcss_ServerInfo;

static const RPC_SERVER_INTERFACE Irpcss___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0x85da4974,0xedc7,0x40ff,{0xba,0xd4,0x9c,0x45,0x25,0xa8,0xd0,0x44}},{0,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &Irpcss_v0_0_DispatchTable,
    0,
    0,
    0,
    &Irpcss_ServerInfo,
    0,
};
RPC_IF_HANDLE Irpcss_v0_0_s_ifspec DECLSPEC_HIDDEN = (RPC_IF_HANDLE)& Irpcss___RpcServerInterface;

static const MIDL_STUB_DESC Irpcss_StubDesc;

struct __frame_Irpcss_irpcss_server_register
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    HRESULT _RetVal;
    handle_t handle;
    const GUID * clsid;
    unsigned int flags;
    PMInterfacePointer object;
    unsigned int _W0;
    unsigned int * cookie;
};

static void __finally_Irpcss_irpcss_server_register( struct __frame_Irpcss_irpcss_server_register *__frame )
{



    NdrPointerFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->object,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[54]);



}

void __RPC_STUB Irpcss_irpcss_server_register( PRPC_MESSAGE _pRpcMessage )
{
    struct __frame_Irpcss_irpcss_server_register __f, * const __frame = &__f;
    RPC_STATUS _Status;

    NdrServerInitializeNew(
        _pRpcMessage,
        &__frame->_StubMsg,
        &Irpcss_StubDesc);

    RpcExceptionInit( __server_filter, __finally_Irpcss_irpcss_server_register );
    __frame->clsid = 0;
    __frame->object = 0;
    __frame->cookie = 0;

    __frame->handle = _pRpcMessage->Handle;

    RpcTryFinally
    {
        RpcTryExcept
        {
            if ((_pRpcMessage->DataRepresentation & 0x0000FFFFUL) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert(&__frame->_StubMsg, (PFORMAT_STRING)&__MIDL_ProcFormatString.Format[0]);


            NdrSimpleStructUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&__frame->clsid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[8],
                0);

            __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(unsigned int) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            __frame->flags = *(unsigned int *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(unsigned int);

            NdrPointerUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&__frame->object,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[54],
                0);

            if (__frame->_StubMsg.Buffer > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
        }
        RpcExcept(RPC_BAD_STUB_DATA_EXCEPTION_FILTER)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        RpcEndExcept

        __frame->cookie = &__frame->_W0;
        __frame->_W0 = 0;

        __frame->_RetVal = irpcss_server_register(
            __frame->handle,
            __frame->clsid,
            __frame->flags,
            __frame->object,
            __frame->cookie);
        __frame->_StubMsg.BufferLength = 16;
        _pRpcMessage->BufferLength = __frame->_StubMsg.BufferLength;

        _Status = I_RpcGetBuffer(_pRpcMessage);
        if (_Status)
            RpcRaiseException(_Status);

        __frame->_StubMsg.Buffer = _pRpcMessage->Buffer;

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(unsigned int *)__frame->_StubMsg.Buffer = *__frame->cookie;
        __frame->_StubMsg.Buffer += sizeof(unsigned int);

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_Irpcss_irpcss_server_register( __frame );
    }
    RpcEndFinally

    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
}

struct __frame_Irpcss_irpcss_server_revoke
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    HRESULT _RetVal;
    handle_t handle;
    unsigned int cookie;
};

static void __finally_Irpcss_irpcss_server_revoke( struct __frame_Irpcss_irpcss_server_revoke *__frame )
{



}

void __RPC_STUB Irpcss_irpcss_server_revoke( PRPC_MESSAGE _pRpcMessage )
{
    struct __frame_Irpcss_irpcss_server_revoke __f, * const __frame = &__f;
    RPC_STATUS _Status;

    NdrServerInitializeNew(
        _pRpcMessage,
        &__frame->_StubMsg,
        &Irpcss_StubDesc);

    RpcExceptionInit( __server_filter, __finally_Irpcss_irpcss_server_revoke );

    __frame->handle = _pRpcMessage->Handle;

    RpcTryFinally
    {
        RpcTryExcept
        {
            if ((_pRpcMessage->DataRepresentation & 0x0000FFFFUL) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert(&__frame->_StubMsg, (PFORMAT_STRING)&__MIDL_ProcFormatString.Format[18]);


            __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
            if (__frame->_StubMsg.Buffer + sizeof(unsigned int) > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
            __frame->cookie = *(unsigned int *)__frame->_StubMsg.Buffer;
            __frame->_StubMsg.Buffer += sizeof(unsigned int);

            if (__frame->_StubMsg.Buffer > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
        }
        RpcExcept(RPC_BAD_STUB_DATA_EXCEPTION_FILTER)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        RpcEndExcept

        __frame->_RetVal = irpcss_server_revoke(
            __frame->handle,
            __frame->cookie);
        __frame->_StubMsg.BufferLength = 8;
        _pRpcMessage->BufferLength = __frame->_StubMsg.BufferLength;

        _Status = I_RpcGetBuffer(_pRpcMessage);
        if (_Status)
            RpcRaiseException(_Status);

        __frame->_StubMsg.Buffer = _pRpcMessage->Buffer;

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_Irpcss_irpcss_server_revoke( __frame );
    }
    RpcEndFinally

    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
}

struct __frame_Irpcss_irpcss_get_class_object
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    HRESULT _RetVal;
    handle_t handle;
    const GUID * clsid;
    PMInterfacePointer _W0;
    PMInterfacePointer * object;
};

static void __finally_Irpcss_irpcss_get_class_object( struct __frame_Irpcss_irpcss_get_class_object *__frame )
{


    NdrPointerFree(
        &__frame->_StubMsg,
        (unsigned char *)__frame->object,
        (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[58]);


}

void __RPC_STUB Irpcss_irpcss_get_class_object( PRPC_MESSAGE _pRpcMessage )
{
    struct __frame_Irpcss_irpcss_get_class_object __f, * const __frame = &__f;
    RPC_STATUS _Status;

    NdrServerInitializeNew(
        _pRpcMessage,
        &__frame->_StubMsg,
        &Irpcss_StubDesc);

    RpcExceptionInit( __server_filter, __finally_Irpcss_irpcss_get_class_object );
    __frame->clsid = 0;
    __frame->object = 0;

    __frame->handle = _pRpcMessage->Handle;

    RpcTryFinally
    {
        RpcTryExcept
        {
            if ((_pRpcMessage->DataRepresentation & 0x0000FFFFUL) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert(&__frame->_StubMsg, (PFORMAT_STRING)&__MIDL_ProcFormatString.Format[24]);


            NdrSimpleStructUnmarshall(
                &__frame->_StubMsg,
                (unsigned char **)&__frame->clsid,
                (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[8],
                0);

            if (__frame->_StubMsg.Buffer > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
        }
        RpcExcept(RPC_BAD_STUB_DATA_EXCEPTION_FILTER)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        RpcEndExcept

        __frame->object = &__frame->_W0;
        __frame->_W0 = 0;

        __frame->_RetVal = irpcss_get_class_object(
            __frame->handle,
            __frame->clsid,
            __frame->object);
        __frame->_StubMsg.BufferLength = 8;
        NdrPointerBufferSize(
            &__frame->_StubMsg,
            (unsigned char *)__frame->object,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[58]);

        _pRpcMessage->BufferLength = __frame->_StubMsg.BufferLength;

        _Status = I_RpcGetBuffer(_pRpcMessage);
        if (_Status)
            RpcRaiseException(_Status);

        __frame->_StubMsg.Buffer = _pRpcMessage->Buffer;

        NdrPointerMarshall(
            &__frame->_StubMsg,
            (unsigned char *)__frame->object,
            (PFORMAT_STRING)&__MIDL_TypeFormatString.Format[58]);

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_Irpcss_irpcss_get_class_object( __frame );
    }
    RpcEndFinally

    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
}

struct __frame_Irpcss_irpcss_get_thread_seq_id
{
    __DECL_EXCEPTION_FRAME
    MIDL_STUB_MESSAGE _StubMsg;
    HRESULT _RetVal;
    handle_t handle;
    DWORD _W0;
    DWORD * sequence_id;
};

static void __finally_Irpcss_irpcss_get_thread_seq_id( struct __frame_Irpcss_irpcss_get_thread_seq_id *__frame )
{



}

void __RPC_STUB Irpcss_irpcss_get_thread_seq_id( PRPC_MESSAGE _pRpcMessage )
{
    struct __frame_Irpcss_irpcss_get_thread_seq_id __f, * const __frame = &__f;
    RPC_STATUS _Status;

    NdrServerInitializeNew(
        _pRpcMessage,
        &__frame->_StubMsg,
        &Irpcss_StubDesc);

    RpcExceptionInit( __server_filter, __finally_Irpcss_irpcss_get_thread_seq_id );
    __frame->sequence_id = 0;

    __frame->handle = _pRpcMessage->Handle;

    RpcTryFinally
    {
        RpcTryExcept
        {
            if ((_pRpcMessage->DataRepresentation & 0x0000FFFFUL) != NDR_LOCAL_DATA_REPRESENTATION)
                NdrConvert(&__frame->_StubMsg, (PFORMAT_STRING)&__MIDL_ProcFormatString.Format[36]);


            if (__frame->_StubMsg.Buffer > __frame->_StubMsg.BufferEnd)
            {
                RpcRaiseException(RPC_X_BAD_STUB_DATA);
            }
        }
        RpcExcept(RPC_BAD_STUB_DATA_EXCEPTION_FILTER)
        {
            RpcRaiseException(RPC_X_BAD_STUB_DATA);
        }
        RpcEndExcept

        __frame->sequence_id = &__frame->_W0;
        __frame->_W0 = 0;

        __frame->_RetVal = irpcss_get_thread_seq_id(
            __frame->handle,
            __frame->sequence_id);
        __frame->_StubMsg.BufferLength = 16;
        _pRpcMessage->BufferLength = __frame->_StubMsg.BufferLength;

        _Status = I_RpcGetBuffer(_pRpcMessage);
        if (_Status)
            RpcRaiseException(_Status);

        __frame->_StubMsg.Buffer = _pRpcMessage->Buffer;

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(DWORD *)__frame->_StubMsg.Buffer = *__frame->sequence_id;
        __frame->_StubMsg.Buffer += sizeof(DWORD);

        MIDL_memset(__frame->_StubMsg.Buffer, 0, (0x4 - (ULONG_PTR)__frame->_StubMsg.Buffer) & 0x3);
        __frame->_StubMsg.Buffer = (unsigned char *)(((ULONG_PTR)__frame->_StubMsg.Buffer + 3) & ~0x3);
        *(HRESULT *)__frame->_StubMsg.Buffer = __frame->_RetVal;
        __frame->_StubMsg.Buffer += sizeof(HRESULT);

    }
    RpcFinally
    {
        __finally_Irpcss_irpcss_get_thread_seq_id( __frame );
    }
    RpcEndFinally

    _pRpcMessage->BufferLength = __frame->_StubMsg.Buffer - (unsigned char *)_pRpcMessage->Buffer;
}

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short Irpcss_FormatStringOffsetTable[] =
{
    0,  /* irpcss_server_register */
    18,  /* irpcss_server_revoke */
    24,  /* irpcss_get_class_object */
    36,  /* irpcss_get_thread_seq_id */
};

static const MIDL_STUB_DESC Irpcss_StubDesc =
{
    (void *)& Irpcss___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x10001, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION Irpcss_table[] =
{
    Irpcss_irpcss_server_register,
    Irpcss_irpcss_server_revoke,
    Irpcss_irpcss_get_class_object,
    Irpcss_irpcss_get_thread_seq_id,
    0
};
static RPC_DISPATCH_TABLE Irpcss_v0_0_DispatchTable =
{
    4,
    Irpcss_table
};

static const SERVER_ROUTINE Irpcss_ServerRoutineTable[] =
{
    (void *)irpcss_server_register,
    (void *)irpcss_server_revoke,
    (void *)irpcss_get_class_object,
    (void *)irpcss_get_thread_seq_id,
};

static const MIDL_SERVER_INFO Irpcss_ServerInfo =
{
    &Irpcss_StubDesc,
    Irpcss_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    Irpcss_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (parameter handle) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x0f,    /* FC_IGNORE */
/* 2 (parameter clsid) */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x14),	/* type offset = 20 */
/* 6 (parameter flags) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
/* 8 (parameter object) */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x2a),	/* type offset = 42 */
/* 12 (parameter cookie) */
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0x2e),	/* type offset = 46 */
/* 16 (return value) */
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
/* 18 (parameter handle) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x0f,    /* FC_IGNORE */
/* 20 (parameter cookie) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
/* 22 (return value) */
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
/* 24 (parameter handle) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x0f,    /* FC_IGNORE */
/* 26 (parameter clsid) */
        0x4d,    /* FC_IN_PARAM */
        0x01,
        NdrFcShort(0x32),	/* type offset = 50 */
/* 30 (parameter object) */
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0x3a),	/* type offset = 58 */
/* 34 (return value) */
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
/* 36 (parameter handle) */
        0x4e,    /* FC_IN_PARAM_BASETYPE */
        0x0f,    /* FC_IGNORE */
/* 38 (parameter sequence_id) */
        0x51,    /* FC_OUT_PARAM */
        0x01,
        NdrFcShort(0x3e),	/* type offset = 62 */
/* 42 (return value) */
        0x53,    /* FC_RETURN_PARAM_BASETYPE */
        0x08,    /* FC_LONG */
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 8 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,	/* FC_END */
/* 20 (const GUID *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (8) */
/* 24 (BYTE[]) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x9,	/* Corr desc: field ulCntData, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 34 (MInterfacePointer) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        NdrFcShort(0xfff2),	/* Offset= -14 (24) */
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 42 (PMInterfacePointer) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff6),	/* Offset= -10 (34) */
/* 46 (unsigned int *) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 50 (const GUID *) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd4),	/* Offset= -44 (8) */
/* 54 (PMInterfacePointer) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffea),	/* Offset= -22 (34) */
/* 58 (PMInterfacePointer *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (54) */
/* 62 (DWORD *) */
        0x11, 0xc,	/* FC_RP [allocated_on_stack] [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
        0x0
    }
};

