/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_concrt140(void);

const struct test winetest_testlist[] =
{
    { "concrt140", func_concrt140 },
    { 0, 0 }
};
