/*** Autogenerated by WIDL 8.6 from dlls/oleaut32/tests/test_simple.idl - Do not edit ***/

#include <rpc.h>
#include <rpcndr.h>

#ifdef _MIDL_USE_GUIDDEF_

#ifndef INITGUID
#define INITGUID
#include <guiddef.h>
#undef INITGUID
#else
#include <guiddef.h>
#endif

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    DEFINE_GUID(name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8)

#elif defined(__cplusplus)

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    EXTERN_C const type DECLSPEC_SELECTANY name = {l,w1,w2,{b1,b2,b3,b4,b5,b6,b7,b8}}

#else

#define MIDL_DEFINE_GUID(type,name,l,w1,w2,b1,b2,b3,b4,b5,b6,b7,b8) \
    const type DECLSPEC_SELECTANY name = {l,w1,w2,{b1,b2,b3,b4,b5,b6,b7,b8}}

#endif

#ifdef __cplusplus
extern "C" {
#endif

MIDL_DEFINE_GUID(IID, LIBID_base, 0x8b05fe77, 0x4a6c, 0x4133, 0xb9,0xcd, 0x8f,0x00,0x00,0x7a,0xf7,0x86);
MIDL_DEFINE_GUID(IID, IID_IBaseIface, 0xb14b6bb5, 0x904e, 0x4ff9, 0xb2,0x47, 0xbd,0x36,0x1f,0x7a,0x00,0x04);

#ifdef __cplusplus
}
#endif

#undef MIDL_DEFINE_GUID
