/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_afd(void);
extern void func_protocol(void);
extern void func_sock(void);

const struct test winetest_testlist[] =
{
    { "afd", func_afd },
    { "protocol", func_protocol },
    { "sock", func_sock },
    { 0, 0 }
};
