/*** Autogenerated by WIDL 8.6 from dlls/cryptowinrt/provider.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __provider_h__
#define __provider_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_FWD_DEFINED__
#define ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler ABI::Windows::Security::Credentials::IWineAsyncOperationCompletedHandler
namespace ABI {
    namespace Windows {
        namespace Security {
            namespace Credentials {
                interface IWineAsyncOperationCompletedHandler;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_FWD_DEFINED__
#define ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl ABI::Windows::Security::Credentials::IWineAsyncInfoImpl
namespace ABI {
    namespace Windows {
        namespace Security {
            namespace Credentials {
                interface IWineAsyncInfoImpl;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <propidl.h>
#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IWineAsyncOperationCompletedHandler interface
 */
#ifndef ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_INTERFACE_DEFINED__

#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Security {
            namespace Credentials {
                interface IWineAsyncOperationCompletedHandler : public IUnknown
                {
                    virtual HRESULT STDMETHODCALLTYPE Invoke(
                        IInspectable *async,
                        AsyncStatus status) = 0;

                };
            }
        }
    }
}
extern "C" {
#else
typedef struct __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandlerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *This);

    /*** IWineAsyncOperationCompletedHandler methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *This,
        IInspectable *async,
        AsyncStatus status);

    END_INTERFACE
} __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandlerVtbl;

interface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler {
    CONST_VTBL __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandlerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Release(This) (This)->lpVtbl->Release(This)
/*** IWineAsyncOperationCompletedHandler methods ***/
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Invoke(This,async,status) (This)->lpVtbl->Invoke(This,async,status)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_QueryInterface(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_AddRef(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Release(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler* This) {
    return This->lpVtbl->Release(This);
}
/*** IWineAsyncOperationCompletedHandler methods ***/
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Invoke(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler* This,IInspectable *async,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,async,status);
}
#endif
#ifdef WIDL_using_Windows_Security_Credentials
#define IWineAsyncOperationCompletedHandlerVtbl __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandlerVtbl
#define IWineAsyncOperationCompletedHandler __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler
#define IWineAsyncOperationCompletedHandler_QueryInterface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_QueryInterface
#define IWineAsyncOperationCompletedHandler_AddRef __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_AddRef
#define IWineAsyncOperationCompletedHandler_Release __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Release
#define IWineAsyncOperationCompletedHandler_Invoke __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_Invoke
#endif /* WIDL_using_Windows_Security_Credentials */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IWineAsyncInfoImpl interface
 */
#ifndef ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl, 0x83f377ee, 0xc799, 0x11ec, 0x9d,0x64, 0x02,0x42,0xac,0x12,0x00,0x02);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Security {
            namespace Credentials {
                MIDL_INTERFACE("83f377ee-c799-11ec-9d64-0242ac120002")
                IWineAsyncInfoImpl : public IUnknown
                {
                    virtual HRESULT STDMETHODCALLTYPE put_Completed(
                        ABI::Windows::Security::Credentials::IWineAsyncOperationCompletedHandler *handler) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Completed(
                        ABI::Windows::Security::Credentials::IWineAsyncOperationCompletedHandler **handler) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Result(
                        PROPVARIANT *result) = 0;

                    virtual HRESULT STDMETHODCALLTYPE Start(
                        ) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl, 0x83f377ee, 0xc799, 0x11ec, 0x9d,0x64, 0x02,0x42,0xac,0x12,0x00,0x02)
#endif
#else
typedef struct __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This);

    /*** IWineAsyncInfoImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This,
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This,
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler **handler);

    HRESULT (STDMETHODCALLTYPE *get_Result)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This,
        PROPVARIANT *result);

    HRESULT (STDMETHODCALLTYPE *Start)(
        __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl *This);

    END_INTERFACE
} __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImplVtbl;

interface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl {
    CONST_VTBL __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IWineAsyncInfoImpl methods ***/
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Result(This,result) (This)->lpVtbl->get_Result(This,result)
#define __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Start(This) (This)->lpVtbl->Start(This)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_QueryInterface(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_AddRef(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Release(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IWineAsyncInfoImpl methods ***/
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_put_Completed(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This,__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Completed(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This,__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncOperationCompletedHandler **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Result(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This,PROPVARIANT *result) {
    return This->lpVtbl->get_Result(This,result);
}
static __WIDL_INLINE HRESULT __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Start(__x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl* This) {
    return This->lpVtbl->Start(This);
}
#endif
#ifdef WIDL_using_Windows_Security_Credentials
#define IID_IWineAsyncInfoImpl IID___x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl
#define IWineAsyncInfoImplVtbl __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImplVtbl
#define IWineAsyncInfoImpl __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl
#define IWineAsyncInfoImpl_QueryInterface __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_QueryInterface
#define IWineAsyncInfoImpl_AddRef __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_AddRef
#define IWineAsyncInfoImpl_Release __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Release
#define IWineAsyncInfoImpl_put_Completed __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_put_Completed
#define IWineAsyncInfoImpl_get_Completed __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Completed
#define IWineAsyncInfoImpl_get_Result __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_get_Result
#define IWineAsyncInfoImpl_Start __x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_Start
#endif /* WIDL_using_Windows_Security_Credentials */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CSecurity_CCredentials_CIWineAsyncInfoImpl_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER LPSAFEARRAY_UserSize     (ULONG *, ULONG, LPSAFEARRAY *);
unsigned char * __RPC_USER LPSAFEARRAY_UserMarshal  (ULONG *, unsigned char *, LPSAFEARRAY *);
unsigned char * __RPC_USER LPSAFEARRAY_UserUnmarshal(ULONG *, unsigned char *, LPSAFEARRAY *);
void            __RPC_USER LPSAFEARRAY_UserFree     (ULONG *, LPSAFEARRAY *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __provider_h__ */
