/*** Autogenerated by WIDL 8.6 from dlls/msi/tests/typelib.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __typelib_h__
#define __typelib_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

#ifndef __register_test_LIBRARY_DEFINED__
#define __register_test_LIBRARY_DEFINED__

DEFINE_GUID(LIBID_register_test, 0xeac5166a, 0x9734, 0x4d91, 0x87,0x8f, 0x1d,0xd0,0x23,0x04,0xc6,0x6c);

#endif /* __register_test_LIBRARY_DEFINED__ */
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __typelib_h__ */
