/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_msvcp140_1(void);

const struct test winetest_testlist[] =
{
    { "msvcp140_1", func_msvcp140_1 },
    { 0, 0 }
};
