/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_asfreader(void);
extern void func_dmowrapper(void);

const struct test winetest_testlist[] =
{
    { "asfreader", func_asfreader },
    { "dmowrapper", func_dmowrapper },
    { 0, 0 }
};
