/*** Autogenerated by WIDL 8.6 from dlls/diasymreader/diasymreader.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __diasymreader_h__
#define __diasymreader_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __IPdbWriter_FWD_DEFINED__
#define __IPdbWriter_FWD_DEFINED__
typedef interface IPdbWriter IPdbWriter;
#ifdef __cplusplus
interface IPdbWriter;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <unknwn.h>
#include <objidl.h>
#include <oaidl.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IPdbWriter interface
 */
#ifndef __IPdbWriter_INTERFACE_DEFINED__
#define __IPdbWriter_INTERFACE_DEFINED__

DEFINE_GUID(IID_IPdbWriter, 0x98ecee1e, 0x752d, 0x11d3, 0x8d,0x56, 0x00,0xc0,0x4f,0x68,0x0b,0x2b);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("98ecee1e-752d-11d3-8d56-00c04f680b2b")
IPdbWriter : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE SetPath(
        const WCHAR *fullpath,
        IStream *stream,
        BOOL fullbuild) = 0;

    virtual HRESULT STDMETHODCALLTYPE OpenMod(
        const WCHAR *modulename,
        const WCHAR *filename) = 0;

    virtual HRESULT STDMETHODCALLTYPE CloseMod(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetPath(
        DWORD ccData,
        DWORD *pccData,
        WCHAR *path) = 0;

    virtual HRESULT STDMETHODCALLTYPE GetSignatureAge(
        DWORD *timestamp,
        DWORD *age) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IPdbWriter, 0x98ecee1e, 0x752d, 0x11d3, 0x8d,0x56, 0x00,0xc0,0x4f,0x68,0x0b,0x2b)
#endif
#else
typedef struct IPdbWriterVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IPdbWriter *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IPdbWriter *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IPdbWriter *This);

    /*** IPdbWriter methods ***/
    HRESULT (STDMETHODCALLTYPE *SetPath)(
        IPdbWriter *This,
        const WCHAR *fullpath,
        IStream *stream,
        BOOL fullbuild);

    HRESULT (STDMETHODCALLTYPE *OpenMod)(
        IPdbWriter *This,
        const WCHAR *modulename,
        const WCHAR *filename);

    HRESULT (STDMETHODCALLTYPE *CloseMod)(
        IPdbWriter *This);

    HRESULT (STDMETHODCALLTYPE *GetPath)(
        IPdbWriter *This,
        DWORD ccData,
        DWORD *pccData,
        WCHAR *path);

    HRESULT (STDMETHODCALLTYPE *GetSignatureAge)(
        IPdbWriter *This,
        DWORD *timestamp,
        DWORD *age);

    END_INTERFACE
} IPdbWriterVtbl;

interface IPdbWriter {
    CONST_VTBL IPdbWriterVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IPdbWriter_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IPdbWriter_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IPdbWriter_Release(This) (This)->lpVtbl->Release(This)
/*** IPdbWriter methods ***/
#define IPdbWriter_SetPath(This,fullpath,stream,fullbuild) (This)->lpVtbl->SetPath(This,fullpath,stream,fullbuild)
#define IPdbWriter_OpenMod(This,modulename,filename) (This)->lpVtbl->OpenMod(This,modulename,filename)
#define IPdbWriter_CloseMod(This) (This)->lpVtbl->CloseMod(This)
#define IPdbWriter_GetPath(This,ccData,pccData,path) (This)->lpVtbl->GetPath(This,ccData,pccData,path)
#define IPdbWriter_GetSignatureAge(This,timestamp,age) (This)->lpVtbl->GetSignatureAge(This,timestamp,age)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IPdbWriter_QueryInterface(IPdbWriter* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG IPdbWriter_AddRef(IPdbWriter* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IPdbWriter_Release(IPdbWriter* This) {
    return This->lpVtbl->Release(This);
}
/*** IPdbWriter methods ***/
static __WIDL_INLINE HRESULT IPdbWriter_SetPath(IPdbWriter* This,const WCHAR *fullpath,IStream *stream,BOOL fullbuild) {
    return This->lpVtbl->SetPath(This,fullpath,stream,fullbuild);
}
static __WIDL_INLINE HRESULT IPdbWriter_OpenMod(IPdbWriter* This,const WCHAR *modulename,const WCHAR *filename) {
    return This->lpVtbl->OpenMod(This,modulename,filename);
}
static __WIDL_INLINE HRESULT IPdbWriter_CloseMod(IPdbWriter* This) {
    return This->lpVtbl->CloseMod(This);
}
static __WIDL_INLINE HRESULT IPdbWriter_GetPath(IPdbWriter* This,DWORD ccData,DWORD *pccData,WCHAR *path) {
    return This->lpVtbl->GetPath(This,ccData,pccData,path);
}
static __WIDL_INLINE HRESULT IPdbWriter_GetSignatureAge(IPdbWriter* This,DWORD *timestamp,DWORD *age) {
    return This->lpVtbl->GetSignatureAge(This,timestamp,age);
}
#endif
#endif

#endif


#endif  /* __IPdbWriter_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __diasymreader_h__ */
