/*** Autogenerated by WIDL 8.6 from dlls/uiautomationcore/uia_classes.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __uia_classes_h__
#define __uia_classes_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __IWineUiaProvider_FWD_DEFINED__
#define __IWineUiaProvider_FWD_DEFINED__
typedef interface IWineUiaProvider IWineUiaProvider;
#ifdef __cplusplus
interface IWineUiaProvider;
#endif /* __cplusplus */
#endif

#ifndef __IWineUiaNode_FWD_DEFINED__
#define __IWineUiaNode_FWD_DEFINED__
typedef interface IWineUiaNode IWineUiaNode;
#ifdef __cplusplus
interface IWineUiaNode;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oaidl.h>

#ifdef __cplusplus
extern "C" {
#endif

struct uia_prop_info {
    const GUID *guid;
    int prop_id;
    int prop_type;
    int type;
    int pattern_id;
};
struct uia_event_info {
    const GUID *guid;
    int event_id;
    int event_arg_type;
};
struct uia_pattern_info {
    const GUID *guid;
    int pattern_id;
    const GUID *pattern_iid;
};
struct uia_control_type_info {
    const GUID *guid;
    int control_type_id;
};
#ifndef __UIA_wine_private_LIBRARY_DEFINED__
#define __UIA_wine_private_LIBRARY_DEFINED__

DEFINE_GUID(LIBID_UIA_wine_private, 0x8a9ca8eb, 0x856b, 0x43d9, 0xab,0xd7, 0x4a,0x59,0x00,0x54,0x06,0x4f);

/*****************************************************************************
 * IWineUiaProvider interface
 */
#ifndef __IWineUiaProvider_INTERFACE_DEFINED__
#define __IWineUiaProvider_INTERFACE_DEFINED__

DEFINE_GUID(IID_IWineUiaProvider, 0x57865755, 0x6c05, 0x4522, 0x98,0xdf, 0x4c,0xa6,0x58,0xb7,0x68,0xef);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("57865755-6c05-4522-98df-4ca658b768ef")
IWineUiaProvider : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE get_prop_val(
        const struct uia_prop_info *prop_info,
        VARIANT *ret_val) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_prov_opts(
        int *out_opts) = 0;

    virtual HRESULT STDMETHODCALLTYPE has_parent(
        BOOL *out_val) = 0;

    virtual HRESULT STDMETHODCALLTYPE navigate(
        int nav_dir,
        VARIANT *ret_val) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IWineUiaProvider, 0x57865755, 0x6c05, 0x4522, 0x98,0xdf, 0x4c,0xa6,0x58,0xb7,0x68,0xef)
#endif
#else
typedef struct IWineUiaProviderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IWineUiaProvider *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IWineUiaProvider *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IWineUiaProvider *This);

    /*** IWineUiaProvider methods ***/
    HRESULT (STDMETHODCALLTYPE *get_prop_val)(
        IWineUiaProvider *This,
        const struct uia_prop_info *prop_info,
        VARIANT *ret_val);

    HRESULT (STDMETHODCALLTYPE *get_prov_opts)(
        IWineUiaProvider *This,
        int *out_opts);

    HRESULT (STDMETHODCALLTYPE *has_parent)(
        IWineUiaProvider *This,
        BOOL *out_val);

    HRESULT (STDMETHODCALLTYPE *navigate)(
        IWineUiaProvider *This,
        int nav_dir,
        VARIANT *ret_val);

    END_INTERFACE
} IWineUiaProviderVtbl;

interface IWineUiaProvider {
    CONST_VTBL IWineUiaProviderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IWineUiaProvider_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IWineUiaProvider_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IWineUiaProvider_Release(This) (This)->lpVtbl->Release(This)
/*** IWineUiaProvider methods ***/
#define IWineUiaProvider_get_prop_val(This,prop_info,ret_val) (This)->lpVtbl->get_prop_val(This,prop_info,ret_val)
#define IWineUiaProvider_get_prov_opts(This,out_opts) (This)->lpVtbl->get_prov_opts(This,out_opts)
#define IWineUiaProvider_has_parent(This,out_val) (This)->lpVtbl->has_parent(This,out_val)
#define IWineUiaProvider_navigate(This,nav_dir,ret_val) (This)->lpVtbl->navigate(This,nav_dir,ret_val)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IWineUiaProvider_QueryInterface(IWineUiaProvider* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG IWineUiaProvider_AddRef(IWineUiaProvider* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IWineUiaProvider_Release(IWineUiaProvider* This) {
    return This->lpVtbl->Release(This);
}
/*** IWineUiaProvider methods ***/
static __WIDL_INLINE HRESULT IWineUiaProvider_get_prop_val(IWineUiaProvider* This,const struct uia_prop_info *prop_info,VARIANT *ret_val) {
    return This->lpVtbl->get_prop_val(This,prop_info,ret_val);
}
static __WIDL_INLINE HRESULT IWineUiaProvider_get_prov_opts(IWineUiaProvider* This,int *out_opts) {
    return This->lpVtbl->get_prov_opts(This,out_opts);
}
static __WIDL_INLINE HRESULT IWineUiaProvider_has_parent(IWineUiaProvider* This,BOOL *out_val) {
    return This->lpVtbl->has_parent(This,out_val);
}
static __WIDL_INLINE HRESULT IWineUiaProvider_navigate(IWineUiaProvider* This,int nav_dir,VARIANT *ret_val) {
    return This->lpVtbl->navigate(This,nav_dir,ret_val);
}
#endif
#endif

#endif


#endif  /* __IWineUiaProvider_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IWineUiaNode interface
 */
#ifndef __IWineUiaNode_INTERFACE_DEFINED__
#define __IWineUiaNode_INTERFACE_DEFINED__

DEFINE_GUID(IID_IWineUiaNode, 0xbccb6799, 0xd831, 0x4057, 0xbd,0x50, 0x64,0x25,0x82,0x3f,0xf1,0xa3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("bccb6799-d831-4057-bd50-6425823ff1a3")
IWineUiaNode : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE get_provider(
        int idx,
        IWineUiaProvider **out_prov) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_prop_val(
        const GUID *prop_guid,
        VARIANT *ret_val) = 0;

    virtual HRESULT STDMETHODCALLTYPE disconnect(
        ) = 0;

    virtual HRESULT STDMETHODCALLTYPE get_hwnd(
        ULONG *out_hwnd) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IWineUiaNode, 0xbccb6799, 0xd831, 0x4057, 0xbd,0x50, 0x64,0x25,0x82,0x3f,0xf1,0xa3)
#endif
#else
typedef struct IWineUiaNodeVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IWineUiaNode *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IWineUiaNode *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IWineUiaNode *This);

    /*** IWineUiaNode methods ***/
    HRESULT (STDMETHODCALLTYPE *get_provider)(
        IWineUiaNode *This,
        int idx,
        IWineUiaProvider **out_prov);

    HRESULT (STDMETHODCALLTYPE *get_prop_val)(
        IWineUiaNode *This,
        const GUID *prop_guid,
        VARIANT *ret_val);

    HRESULT (STDMETHODCALLTYPE *disconnect)(
        IWineUiaNode *This);

    HRESULT (STDMETHODCALLTYPE *get_hwnd)(
        IWineUiaNode *This,
        ULONG *out_hwnd);

    END_INTERFACE
} IWineUiaNodeVtbl;

interface IWineUiaNode {
    CONST_VTBL IWineUiaNodeVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IWineUiaNode_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IWineUiaNode_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IWineUiaNode_Release(This) (This)->lpVtbl->Release(This)
/*** IWineUiaNode methods ***/
#define IWineUiaNode_get_provider(This,idx,out_prov) (This)->lpVtbl->get_provider(This,idx,out_prov)
#define IWineUiaNode_get_prop_val(This,prop_guid,ret_val) (This)->lpVtbl->get_prop_val(This,prop_guid,ret_val)
#define IWineUiaNode_disconnect(This) (This)->lpVtbl->disconnect(This)
#define IWineUiaNode_get_hwnd(This,out_hwnd) (This)->lpVtbl->get_hwnd(This,out_hwnd)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT IWineUiaNode_QueryInterface(IWineUiaNode* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG IWineUiaNode_AddRef(IWineUiaNode* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG IWineUiaNode_Release(IWineUiaNode* This) {
    return This->lpVtbl->Release(This);
}
/*** IWineUiaNode methods ***/
static __WIDL_INLINE HRESULT IWineUiaNode_get_provider(IWineUiaNode* This,int idx,IWineUiaProvider **out_prov) {
    return This->lpVtbl->get_provider(This,idx,out_prov);
}
static __WIDL_INLINE HRESULT IWineUiaNode_get_prop_val(IWineUiaNode* This,const GUID *prop_guid,VARIANT *ret_val) {
    return This->lpVtbl->get_prop_val(This,prop_guid,ret_val);
}
static __WIDL_INLINE HRESULT IWineUiaNode_disconnect(IWineUiaNode* This) {
    return This->lpVtbl->disconnect(This);
}
static __WIDL_INLINE HRESULT IWineUiaNode_get_hwnd(IWineUiaNode* This,ULONG *out_hwnd) {
    return This->lpVtbl->get_hwnd(This,out_hwnd);
}
#endif
#endif

#endif


#endif  /* __IWineUiaNode_INTERFACE_DEFINED__ */

#endif /* __UIA_wine_private_LIBRARY_DEFINED__ */
/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER VARIANT_UserSize     (ULONG *, ULONG, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserMarshal  (ULONG *, unsigned char *, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserUnmarshal(ULONG *, unsigned char *, VARIANT *);
void            __RPC_USER VARIANT_UserFree     (ULONG *, VARIANT *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __uia_classes_h__ */
