/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_ldap(void);
extern void func_sysinfo(void);

const struct test winetest_testlist[] =
{
    { "ldap", func_ldap },
    { "sysinfo", func_sysinfo },
    { 0, 0 }
};
