/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_xact3(void);

const struct test winetest_testlist[] =
{
    { "xact3", func_xact3 },
    { 0, 0 }
};
