/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_speech(void);

const struct test winetest_testlist[] =
{
    { "speech", func_speech },
    { 0, 0 }
};
