/*** Autogenerated by WIDL 8.6 from dlls/rpcrt4/tests/cstub.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __cstub_h__
#define __cstub_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __ITest1_FWD_DEFINED__
#define __ITest1_FWD_DEFINED__
typedef interface ITest1 ITest1;
#ifdef __cplusplus
interface ITest1;
#endif /* __cplusplus */
#endif

#ifndef __test_ps_FWD_DEFINED__
#define __test_ps_FWD_DEFINED__
#ifdef __cplusplus
typedef class test_ps test_ps;
#else
typedef struct test_ps test_ps;
#endif /* defined __cplusplus */
#endif /* defined __test_ps_FWD_DEFINED__ */

/* Headers for imported files */

#include <oleidl.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * ITest1 interface
 */
#ifndef __ITest1_INTERFACE_DEFINED__
#define __ITest1_INTERFACE_DEFINED__

DEFINE_GUID(IID_ITest1, 0xdeadbeef, 0x0001, 0x44c7, 0x85,0x0f, 0x2a,0x0f,0x46,0x5c,0x0c,0x6c);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("deadbeef-0001-44c7-850f-2a0f465c0c6c")
ITest1 : public IPersist
{
    virtual int STDMETHODCALLTYPE square(
        int x) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(ITest1, 0xdeadbeef, 0x0001, 0x44c7, 0x85,0x0f, 0x2a,0x0f,0x46,0x5c,0x0c,0x6c)
#endif
#else
typedef struct ITest1Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        ITest1 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        ITest1 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        ITest1 *This);

    /*** IPersist methods ***/
    HRESULT (STDMETHODCALLTYPE *GetClassID)(
        ITest1 *This,
        CLSID *pClassID);

    /*** ITest1 methods ***/
    int (STDMETHODCALLTYPE *square)(
        ITest1 *This,
        int x);

    END_INTERFACE
} ITest1Vtbl;

interface ITest1 {
    CONST_VTBL ITest1Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define ITest1_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define ITest1_AddRef(This) (This)->lpVtbl->AddRef(This)
#define ITest1_Release(This) (This)->lpVtbl->Release(This)
/*** IPersist methods ***/
#define ITest1_GetClassID(This,pClassID) (This)->lpVtbl->GetClassID(This,pClassID)
/*** ITest1 methods ***/
#define ITest1_square(This,x) (This)->lpVtbl->square(This,x)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT ITest1_QueryInterface(ITest1* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static __WIDL_INLINE ULONG ITest1_AddRef(ITest1* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG ITest1_Release(ITest1* This) {
    return This->lpVtbl->Release(This);
}
/*** IPersist methods ***/
static __WIDL_INLINE HRESULT ITest1_GetClassID(ITest1* This,CLSID *pClassID) {
    return This->lpVtbl->GetClassID(This,pClassID);
}
/*** ITest1 methods ***/
static __WIDL_INLINE int ITest1_square(ITest1* This,int x) {
    return This->lpVtbl->square(This,x);
}
#endif
#endif

#endif


#endif  /* __ITest1_INTERFACE_DEFINED__ */

/*****************************************************************************
 * test_ps coclass
 */

DEFINE_GUID(CLSID_test_ps, 0xdeadbeef, 0xffff, 0x44c7, 0x85,0x0f, 0x2a,0x0f,0x46,0x5c,0x0c,0x6c);

#ifdef __cplusplus
class DECLSPEC_UUID("deadbeef-ffff-44c7-850f-2a0f465c0c6c") test_ps;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(test_ps, 0xdeadbeef, 0xffff, 0x44c7, 0x85,0x0f, 0x2a,0x0f,0x46,0x5c,0x0c,0x6c)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __cstub_h__ */
