/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_nstc(void);
extern void func_taskbarlist(void);

const struct test winetest_testlist[] =
{
    { "nstc", func_nstc },
    { "taskbarlist", func_taskbarlist },
    { 0, 0 }
};
