/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_vcomp110(void);

const struct test winetest_testlist[] =
{
    { "vcomp110", func_vcomp110 },
    { 0, 0 }
};
